import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { IEmployeeLayoutProps } from '../interfaces';

export default function EmployeeLayout({
  children,
  title,
}: IEmployeeLayoutProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Full Stack App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} `}>
        <h1 className={styles.title}>
          Employee <span>{title}</span>
        </h1>
        {children}
      </main>
    </div>
  );
}
