import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { IRegister } from '../interfaces';
import { useForm } from 'react-hook-form';
import { useRouter } from 'next/router';
import { getRequestDeps } from '../lib/functions';
import { useState } from 'react';

export default function Register() {
  const router = useRouter();

  const [serverError, setServerError] = useState<string | null>(null);

  const { fetcher, token } = getRequestDeps();
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<IRegister>();

  const onSubmit = async (data: IRegister) => {
    try {
      const res = await fetcher('/api/user/register', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });
      if (res.status === 200) {
        router.push('/login');
      }
      const dataJson = await res.json();
      if (dataJson.userError) {
        throw new Error(dataJson.userError);
      }
    } catch (error: any) {
      setServerError(error.message);
      setTimeout(() => {
        setServerError(null);
      }, 4000);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Full Stack App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} `}>
        <h1 className={styles.title}>Register</h1>
        {serverError && (
          <p className="error mt-5 mb-5 text-red-500">{serverError}</p>
        )}
        <form
          onSubmit={handleSubmit(onSubmit)}
          className="h-[40rem] w-[20rem] flex-col "
        >
          <div className="border border-solid border-gray-700 mt-10 p-8">
            <div className=" flex flex-col">
              <label htmlFor="email" className="font-semibold mb-2">
                Email
              </label>
              <input
                type="email"
                className="form-control
                w-full
                          self-start
                          px-3
                          py-1.5
                          text-base
                          font-normal
                          text-white
                          border border-solid border-gray-700
                          rounded-lg
                          transition
                          ease-in-out
                          m-0 focus:outline-none  focus-visible:ring-2  focus-visible:ring-opacity-75 focus-visible:ring-offset-2 focus-visible:ring-offset-blue-600 bg-inherit flex-1"
                {...register('email', { required: true })}
                placeholder="Enter email*"
              ></input>
              {errors.email && (
                <p className="text-red-500 mt-3">{errors.email.message}</p>
              )}
            </div>
            <div className="mt-10 flex flex-col ">
              <label htmlFor="username" className="font-semibold mb-2">
                Username
              </label>
              <input
                type="text"
                className="form-control
                w-full
                          self-start
                          px-3
                          py-1.5
                          text-base
                          font-normal
                          text-white
                          border border-solid border-gray-700
                          rounded-lg
                          transition
                          ease-in-out
                          m-0 focus:outline-none  focus-visible:ring-2  focus-visible:ring-opacity-75 focus-visible:ring-offset-2 focus-visible:ring-offset-blue-600 bg-inherit flex-1"
                {...register('username', { required: true })}
                placeholder="Enter username*"
              ></input>
              {errors.password && (
                <p className="text-red-500 mt-3">{errors.password.message}</p>
              )}
            </div>

            <div className="mt-10 flex flex-col ">
              <label htmlFor="password" className="font-semibold mb-2">
                Password
              </label>
              <input
                type="password"
                className="form-control
                w-full
                          self-start
                          px-3
                          py-1.5
                          text-base
                          font-normal
                          text-white
                          border border-solid border-gray-700
                          rounded-lg
                          transition
                          ease-in-out
                          m-0 focus:outline-none  focus-visible:ring-2  focus-visible:ring-opacity-75 focus-visible:ring-offset-2 focus-visible:ring-offset-blue-600 bg-inherit flex-1"
                {...register('password', { required: true })}
                placeholder="Enter password*"
              ></input>
              {errors.password && (
                <p className="text-red-500 mt-3">{errors.password.message}</p>
              )}
            </div>
            <div className="mt-10 flex flex-col ">
              <label htmlFor="confirmPassword" className="font-semibold mb-2">
                Confirm Password
              </label>
              <input
                type="password"
                className="form-control
                w-full
                          self-start
                          px-3
                          py-1.5
                          text-base
                          font-normal
                          text-white
                          border border-solid border-gray-700
                          rounded-lg
                          transition
                          ease-in-out
                          m-0 focus:outline-none  focus-visible:ring-2  focus-visible:ring-opacity-75 focus-visible:ring-offset-2 focus-visible:ring-offset-blue-600 bg-inherit flex-1"
                {...register('confirmPassword', {
                  required: true,
                  validate: (val) => {
                    if (watch('password') !== val) {
                      return 'Passwords do not match';
                    }
                  },
                })}
                placeholder="Confirm Password*"
              ></input>
              {errors.confirmPassword && (
                <p className="text-red-500 mt-3">
                  {errors.confirmPassword.message}
                </p>
              )}
            </div>
            <div className="flex justify-between items-center mt-10">
              <button
                className=" bg-[#0070f3] hover:bg-blue-700 text-white font-bold py-2 px-4 rounded "
                type="submit"
              >
                Register
              </button>
              <div
                className="hover:cursor-pointer text-[#0070f3] hover:text-blue-700 underline"
                onClick={() => router.push('/login')}
              >
                Already registered?
              </div>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
}
